package com.oceanpremium.api.core.enum

enum class AvailabilityStateType(val state: String) {
    AVAILABLE("AVAILABLE"),
    NOT_AVAILABLE("NOT AVAILABLE"),
    AVAILABLE_BUT_ACCESSORY_NOT_AVAILABLE("AVAILABLE BUT ACCESSORY NOT AVAILABLE"),
    PARTIALLY_AVAILABLE("PARTIALLY AVAILABLE"),
    PARTIALLY_AVAILABLE_AND_ACCESSORY_NOT_AVAILABLE("PARTIALLY AVAILABLE AND ACCESSORY NOT AVAILABLE"),
    AVAILABLE_BUT_ACCESSORY_PARTIALLY_AVAILABLE("AVAILABLE BUT ACCESSORY PARTIALLY AVAILABLE"),
    AVAILABLE_BUT_DELAYED("AVAILABLE BUT DELAYED"), // Currently unused
}
