# For full config options, check: https://docs.serverless.com

# The provider of the cloud instance and its needed runtime configuration
provider:
  # Cloud provider
  name: aws
  # JVM
  runtime: java8
  # The S3 Bucket used for deploying the archive
  deploymentBucket: oceanpremium-deploy
  # The RAM size (MB) used by the function
  memorySize: 512
  # The default timeout (seconds)
  timeout: 30

  # The stage to deploy, stages:(dev | test |  stage | prod) - defaults to dev
  #
  # Either deploy through gradle task:
  #
  # $ ./gradlew moduleName: deploy -Pstage=<stage_name> --stacktrace
  #
  # or directly via server-less (which is called by the `deploy` Gradle task):
  #
  # $ sls deploy --region eu-west-1 --verbose --stage <stage_name>
  #
  stage:  ${opt:stage, 'dev'}

# The service name which is used to create the stack
service:
  name: ocean-premium-products-api

# Custom variables
custom:
  apiPrefix: api
  apiVersion: v1
  # results in, for example: api/v1
  apiPathPrefix: ${self:custom.apiPrefix}/${self:custom.apiVersion}

# The default region to be deployed to
region: eu-west-1

# The path and the name of the deploy-able archive
package:
  artifact: build/libs/products-0.0.1-SNAPSHOT-aws.jar

# The functions defined by HTTP verb / path and parameters (CRUD)
functions:
  get-product-api-docs:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-product-api-docs
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/docs
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  get-products:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-products
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  get-product-by-id:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-product-by-id
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/{productId}
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          request:
            parameters:
              paths:
                productId: true
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  get-product-groups:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-product-groups
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/groups
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  get-products-inventory:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-products-inventory
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/inventory
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  post-product-batch-availability:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: post-product-batch-availability
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/availability
          # The HTTP verb
          method: post
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
  post-product-order-placement:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: post-product-order-placement
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/order
          # The HTTP verb
          method: post
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):products.sentry_dsn}
      slack_webhook_jvt: ${file(properties.json):products.slack.webhook_jvt}
      slack_webhook_op: ${file(properties.json):products.slack.webhook_op}
      current_rms_token: ${file(properties.json):products.current_rms.token}
      current_rms_subdomain: ${file(properties.json):products.current_rms.subdomain}
      current_rms_api_url: ${file(properties.json):products.current_rms.api_url}
