# For full config options, check: https://docs.serverless.com

# The provider of the cloud instance and its needed runtime configuration
provider:
  # Cloud provider
  name: aws
  # JVM
  runtime: java8
  # The S3 Bucket used for deploying the archive
  deploymentBucket: oceanpremium-deploy
  # The RAM size (MB) used by the function
  memorySize: 512
  # The default timeout (seconds)
  timeout: 30

  # The stage to deploy, stages:(dev | test |  stage | prod) - defaults to dev
  #
  # Either deploy through gradle task:
  #
  # $ ./gradlew moduleName: deploy -Pstage=<stage_name> --stacktrace
  #
  # or directly via server-less (which is called by the `deploy` Gradle task):
  #
  # $ sls deploy --region eu-west-1 --verbose --stage <stage_name>
  #
  stage:  ${opt:stage, 'dev'}

# The service name which is used to create the stack
service:
  name: ocean-premium-products-api

# Custom variables
custom:
  apiPrefix: api
  apiVersion: v1
  # results in, for example: api/v1
  apiPathPrefix: ${self:custom.apiPrefix}/${self:custom.apiVersion}

# The default region to be deployed to
region: eu-west-1

# The path and the name of the deploy-able archive
package:
  artifact: build/libs/products-0.0.1-SNAPSHOT-aws.jar

# The functions defined by HTTP verb / path and parameters (CRUD)
functions:
  get-product-api-docs:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-product-api-docs
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products/docs
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):Products.SENTRY_DSN}
      SLACK_LOGGER_WEBHOOK: ${file(properties.json):Products.SLACK_LOGGER_WEBHOOK}
  get-products:
    # The function handler to be called for this endpoint
    handler: com.oceanpremium.api.products.Handler::handleRequest
    name: get-products
    events:
      - http:
          # The URI of the endpoint
          path: /${self:custom.apiPathPrefix}/products
          # The HTTP verb
          method: get
          # Additional endpoint configurations like enabling CORS
          cors: true
          # The default headers mandatory for this endpoint
          headers:
            - Content-Type
          allowCredentials: false
    environment:
      SENTRY_DSN: ${file(properties.json):Products.SENTRY_DSN}
      SLACK_LOGGER_WEBHOOK: ${file(properties.json):Products.SLACK_LOGGER_WEBHOOK}
      SLACK_LOGGER_WEBHOOK_OP: ${file(properties.json):Products.SLACK_LOGGER_WEBHOOK_OP}
      CURRENT_RMS_TOKEN: ${file(properties.json):Products.CURRENT_RMS_TOKEN}
      CURRENT_RMS_SUBDOMAIN: ${file(properties.json):Products.CURRENT_RMS_SUBDOMAIN}
